// src/components/LearnMore.jsx
import { motion } from "framer-motion";

export default function LearnMore() {
  return (
    <div
      id="learn-more"
      className="min-h-screen bg-gradient-to-b from-black via-gray-900 to-black text-white px-6 py-20"
    >
      {/* Heading */}
      <motion.h1
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        className="text-4xl md:text-5xl font-bold text-center mb-16"
      >
        Why Choose <span className="text-purple-400">AI Prep?</span>
      </motion.h1>

      {/* FEATURES */}
      <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
        {[
          {
            title: "AI Mock Interviews",
            desc: "Practice real interview questions generated by AI.",
          },
          {
            title: "Resume Analyzer",
            desc: "Upload resume and get insights instantly.",
          },
          {
            title: "AI Feedback",
            desc: "Get scores and suggestions in real-time.",
          },
        ].map((item, i) => (
          <motion.div
            key={i}
            whileHover={{ scale: 1.05 }}
            className="bg-white/10 p-6 rounded-xl border border-white/20 backdrop-blur-lg"
          >
            <h2 className="text-xl text-purple-400 mb-2">{item.title}</h2>
            <p className="text-gray-300">{item.desc}</p>
          </motion.div>
        ))}
      </div>

      {/* HOW IT WORKS */}
      <div className="mt-24 text-center">
        <h2 className="text-3xl font-bold mb-10">How It Works</h2>

        <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {["Upload Resume", "AI Generates Questions", "Get Feedback"].map(
            (step, i) => (
              <motion.div
                key={i}
                whileHover={{ scale: 1.05 }}
                className="bg-white/10 p-6 rounded-xl border border-white/20"
              >
                <h3 className="text-purple-300">Step {i + 1}</h3>
                <p>{step}</p>
              </motion.div>
            )
          )}
        </div>
      </div>

      {/* FEEDBACK PREVIEW */}
      <div className="mt-24 text-center">
        <h2 className="text-3xl mb-10">AI Feedback Preview</h2>

        <div className="max-w-md mx-auto bg-white/10 p-6 rounded-xl border border-white/20 backdrop-blur-lg">
          <p>📊 Score: <span className="text-green-400">82%</span></p>
          <p>💬 Communication: Good</p>
          <p>🧠 Technical: Moderate</p>
        </div>
      </div>

      {/* CTA */}
      <div className="mt-24 text-center">
        <h2 className="text-2xl mb-6">
          Start Your AI Interview Journey 🚀
        </h2>

        <motion.button
          whileHover={{ scale: 1.08 }}
          className="bg-purple-600 px-8 py-3 rounded-xl"
        >
          Get Started
        </motion.button>
      </div>
    </div>
  );
}